# Assignment 5
### Do all four questions.

**1.** Let's review some basic matrix multiplication. When you have an $M \times N$ matrix $A$ with $M$ rows and $N$ columns, 
$$
A= \left[ \begin{array}{cccc} a_{11} & a_{12} & ... & a_{1N} \\
a_{21} & a_{22} & ... & a_{2N} \\
\vdots & \vdots & ... & \vdots \\
a_{M1} & a_{M2} & ... & a_{MN} 
\end{array} \right],
$$
and you right-multiply it by a vector
$$
x = \left[ \begin{array}{c} x_1 \\ x_2 \\ \vdots \\ x_N 
\end{array} \right],
$$
you get
$$
Ax = \left[ \begin{array}{c} \sum_{i=1}^N a_{1i} x_i \\ \sum_{i=1}^N a_{2i} x_i \\ \vdots \\ \sum_{i=1}^N a_{Mi} x_i 
\end{array} \right].
$$
This is just "matrix row times column vector" element-by-element, stacking the results into a new vector.

For this to make sense, $N$ must be the same for the matrix and the vector, but $M$ can be different from $N$. 

Let's play with some NumPy to see this. First we'll define a matrix $A$:

In [2]:
import numpy as np

A = np.array([ [1,2,3],
              [4,5,6],
              [7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

a. Multiply $A$ times each of the following vectors using the @ operator. Explain which part of the $A$ matrix gets selected and explain why, using the definition of matrix multiplication. 

In [3]:
e_1 = np.array([1,0,0])
e_2 = np.array([0,1,0])
e_3 = np.array([0,0,1])

In [4]:
A@e_1, A@e_2, A@e_3

(array([1, 4, 7]), array([2, 5, 8]), array([3, 6, 9]))

e_1, e_2, and e_3 selects the first, second, and third column respectfully from the matrix A. 

b. Now multiply $A$ times $u = (1,1,1)$. Explain the logic of the result with the definition of matrix multiplication.

In [5]:
u = np.ones(3)

In [6]:
A@u

array([ 6., 15., 24.])

This multiplies each column of A by 1 and sums the results, which is equivalent to summing each row of A.

c. Whenever a matrix has 1's on the diagonal and zeros everywhere else, we call it an **identity matrix**. What happens when you multiple $A$ times $x$ below? What happens when you multiple an identity matrix times any vector? Explain your result with the definition of matrix multiplication.

In [7]:
A = np.array([ [1,0,0],
              [0,1,0],
              [0,0,1]])
x = np.array([-2,4,11])


In [8]:
A@x

array([-2,  4, 11])

Multipying any vector by the identity matrix produces the original vector. This is because we are taking the sum of each matrix row (1) by each of the rows in the array.

d. What if every row and column sum to 1, but the 1's are no longer on the diagonal? Multiple $A$ times $X$ below and explain the result. Create another matrix whose rows and columns sum to 1, but is not an identity matrix, and show how it permutes the values of $x$. 

In [9]:
A = np.array([ [0,0,1],
              [1,0,0],
              [0,1,0]])
x = np.array([-2,4,11])


In [10]:
A@x

array([11, -2,  4])

In [15]:
A = np.array([ [0,0,1],
              [0,1,0],
              [1,0,0]])
x = np.array([-2,4,11])

A@x

array([11,  4, -2])

If each row and column sum to 1 but its not the identity matrix the resulting matrix will contain the original array values just not in the original order. The first value in the new array will use the referenced value  in the x array in the first row of the matrix. 

e. The next matrix $A$ could be a Markov transition matrix: Its columns sum to 1, and each entry $a_{ij}$ can be interpreted as the proportion of observations who moved from state $j$ to state $i$. Multiply $A$ by each of the vectors $e_1$, $e_2$, and $e_3$, and explain your results.

In [20]:
rng = np.random.default_rng(100)
A = rng.random((3,3)) # Generate a random 3X3 matrix
sums = np.sum(A,axis=0) # Column sums
A = A/sums # Normalize the columns so they sum to 1
print(A)

[[0.50052958 0.24049286 0.18358131]
 [0.02574731 0.39251588 0.37907577]
 [0.47372311 0.36699127 0.43734292]]


In [21]:
A@e_1, A@e_2, A@e_3 

(array([0.50052958, 0.02574731, 0.47372311]),
 array([0.24049286, 0.39251588, 0.36699127]),
 array([0.18358131, 0.37907577, 0.43734292]))

This takes each col in A of the respectively referenced value in e. For example e1 takes takes the 1st value in each row in the A matrix (essentially taking the entire first column), and so on.

f. For each of the vectors $e_1, e_2, e_3$, multiple $A$ times that vector 5 times. What answer do you get for each starting vector? Describe the behavior you observe.

*2.* Let's consider a simple Markov transition matrix over two states:
$$
T = \left[ \begin{array}{cc} p_{1\leftarrow 1} &  p_{1\leftarrow 2} \\
p_{2 \leftarrow 1} & p_{2 \leftarrow 2} \end{array}\right] 
$$
The arrows help visualize the transition a bit: This is the same index notation as usual, $p_{ij}$, but writing it $p_{i \leftarrow j}$ emphasizes that it's the proportion of times that state $j$ transitions to state $i$. Below, $T$ is given by
$$
T = \left[ \begin{array}{cc} .25 & .5 \\
.75 & .5 \end{array}\right].
$$

- Start in state 1, at the initial condition $[1,0]$. Multiply that vector by $T$. Write out the result in terms of the formula and compute the result in a code chunk below. What is this object you're looking at, in terms of proportions and transitions?
- Multiple by $T$ again. What do you get? This isn't a column of $T$. Explain in words what it is. (Hint: A forecast of what in what period?)
- Keep multiplying the current vector of outcomes by $T$. When does it start to settle down without changing further?
- Do the above analysis again, starting from the initial condition $[0,1]$. Do you get a different result?
- The take-away is that, in the long run, these chains settle down into the long-run proportions, and the sensitivity on initial conditions vanishes. 


In [12]:
T = np.array([[ 1/4, 1/2],
                 [ 3/4, 1/2 ]])

In [24]:
initial_state = np.array([1,0]) # Start in state 1
result = T@initial_state
result

array([0.25, 0.75])

The code above shows that if we start in state 1 we have a 25% chance of staying there and a 75% chance of moving to state 2.

In [26]:
result2 = T@result
result2

array([0.4375, 0.5625])

Given the markov chain. If we start in state 1 the code above shows the probabilities of being in each state after two time steps (emphasis on NOT knowing the result of the first time step). This is a forcast of sorts of what COULD happen given what we know now.

In [ ]:
state = np.array([1,0]) # Start in state 1
for i in range(20):
    print(f"Step {i}: {state}")
    state = T@state

Step 0: [1 0]
Step 1: [0.25 0.75]
Step 2: [0.4375 0.5625]
Step 3: [0.390625 0.609375]
Step 4: [0.40234375 0.59765625]
Step 5: [0.39941406 0.60058594]
Step 6: [0.40014648 0.59985352]
Step 7: [0.39996338 0.60003662]
Step 8: [0.40000916 0.59999084]
Step 9: [0.39999771 0.60000229]
Step 10: [0.40000057 0.59999943]
Step 11: [0.39999986 0.60000014]
Step 12: [0.40000004 0.59999996]
Step 13: [0.39999999 0.60000001]
Step 14: [0.4 0.6]
Step 15: [0.4 0.6]
Step 16: [0.4 0.6]
Step 17: [0.4 0.6]
Step 18: [0.4 0.6]
Step 19: [0.4 0.6]


The resulting vector settles at [0.4 0.6] starting at step 14 but the variance around these two numbers starts to stabilize starting at step 3.

I've ran the code a few times and the result does not change.

3. Weather data

- Load the `cville_weather.csv` data. This includes data from Jan 4, 2024 to Feb 2, 2025. Are there any missing data issues?
- Based on the precipitation variable, `PRCP`, make a new variable called `rain` that takes the value 1 if `PRCP`>0 and 0 otherwise.
- Build a two-state Markov chain over the states 0 and 1 for the `rain` variable. 
- For your chain from c, how likely is it to rain if it was rainy yesterday? How likely is it to rain if it was clear yesterday?
- Starting from a clear day, forecast the distribution. How quickly does it converge to a fixed result? What if you start from a rainy day?
- Conditional on being rainy, plot a KDE of the `PRCP` variable.
- Describe one way of making your model better for forecasting and simulation the weather.

Congratulations, you now are a non-parametric meteorologist!

In [1]:
import pandas as pd

In [3]:
weather = pd.read_csv("cville_weather.csv")
weather.head()

STATION                            NAME        DATE  DAPR  \
0  US1VACRC002  CHARLOTTESVILLE 0.5 NNE, VA US  2024-01-04   NaN   
1  US1VACRC002  CHARLOTTESVILLE 0.5 NNE, VA US  2024-01-07   NaN   
2  US1VACRC002  CHARLOTTESVILLE 0.5 NNE, VA US  2024-01-09   NaN   
3  US1VACRC002  CHARLOTTESVILLE 0.5 NNE, VA US  2024-01-10   NaN   
4  US1VACRC002  CHARLOTTESVILLE 0.5 NNE, VA US  2024-01-24   NaN   

  DAPR_ATTRIBUTES  MDPR MDPR_ATTRIBUTES  PRCP PRCP_ATTRIBUTES  SNOW  \
0             NaN   NaN             NaN  0.03             ,,N   NaN   
1             NaN   NaN             NaN  1.08             ,,N   NaN   
2             NaN   NaN             NaN  0.24             ,,N   NaN   
3             NaN   NaN             NaN  3.00             ,,N   NaN   
4             NaN   NaN             NaN  0.00             ,,N   0.0   

  SNOW_ATTRIBUTES  SNWD SNWD_ATTRIBUTES  
0             NaN   NaN             NaN  
1             NaN   NaN             NaN  
2             NaN   NaN             NaN  
3             NaN   NaN             NaN  
4             ,,N   NaN             NaN

In [4]:
weather.info()
weather.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 411 entries, 0 to 410
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   STATION          411 non-null    object 
 1   NAME             411 non-null    object 
 2   DATE             411 non-null    object 
 3   DAPR             12 non-null     float64
 4   DAPR_ATTRIBUTES  12 non-null     object 
 5   MDPR             12 non-null     float64
 6   MDPR_ATTRIBUTES  12 non-null     object 
 7   PRCP             399 non-null    float64
 8   PRCP_ATTRIBUTES  399 non-null    object 
 9   SNOW             223 non-null    float64
 10  SNOW_ATTRIBUTES  223 non-null    object 
 11  SNWD             1 non-null      float64
 12  SNWD_ATTRIBUTES  1 non-null      object 
dtypes: float64(5), object(8)
memory usage: 41.9+ KB


Index(['STATION', 'NAME', 'DATE', 'DAPR', 'DAPR_ATTRIBUTES', 'MDPR',
       'MDPR_ATTRIBUTES', 'PRCP', 'PRCP_ATTRIBUTES', 'SNOW', 'SNOW_ATTRIBUTES',
       'SNWD', 'SNWD_ATTRIBUTES'],
      dtype='object')

In [9]:
weather["rain"] = weather["PRCP"].apply( lambda x: 1 if x>1 else 0)
weather["rain"].value_counts()

rain
0    386
1     25
Name: count, dtype: int64

2 state markov chain:
0=norain
1=rain

#### NOTE: Super high value is for a taxi cab going from liberty island (HINT HINT ISLAND??) to a different neighborhood.

### Why are taxicabs order 1 and not 2??

In [56]:
#Creating markov chain object:
taxi_markov_chain = MarkovChain(transition_matrix=transition_prob_matrix, state_names=all_neighborhoods)

In [55]:
print(list(all_neighborhoods)[14])

Hell's Kitchen


In [57]:
##Forecasting states:
#Initial point: Hells kitchen
#Steps: 2, 3, 5, and 10 
two_steps = taxi_markov_chain.forecast(2, 14)
three_steps = taxi_markov_chain.forecast(3, 14)
five_steps = taxi_markov_chain.forecast(5, 14)
ten_steps = taxi_markov_chain.forecast(10,14)


In [58]:
import plotly.express as px

In [59]:
from plotly.subplots import make_subplots
import plotly.graph_objects as go

# Create subplots with shared x-axis
fig = make_subplots(
    rows=4, cols=1,
    shared_xaxes=True,
    shared_yaxes=True,
    subplot_titles=("2 Steps", "3 Steps", "5 Steps", "10 Steps"),
    vertical_spacing=0.05
)

# Add each bar chart as a subplot
fig.add_trace(
    go.Bar(x=transition_prob_matrix.columns.values, y=two_steps, name="2 Steps"),
    row=1, col=1
)

fig.add_trace(
    go.Bar(x=transition_prob_matrix.columns.values, y=three_steps, name="3 Steps"),
    row=2, col=1
)

fig.add_trace(
    go.Bar(x=transition_prob_matrix.columns.values, y=five_steps, name="5 Steps"),
    row=3, col=1
)

fig.add_trace(
    go.Bar(x=transition_prob_matrix.columns.values, y=ten_steps, name="10 Steps"),
    row=4, col=1
)

# Update layout
fig.update_xaxes(title_text="Neighborhood", row=4, col=1)
fig.update_yaxes(title_text="Probability")
fig.update_layout(height=800, showlegend=False)

fig.show()